### PR TITLE
fix hdb_catalog.hdb_column view  (fix #3083)

### LINKED ISSUE #3083: Upgrade to v1.0.0-beta.7 causes problems on tables set as enum
Enum tables that comply with the criteria and work perfectly fine in beta.6 cause the beta.7 to fail when starting up. An example message from the logs (schema and table name obfuscated):

{"definition":{"schema":"xxx","name":"yyy"},"reason":"the table \"xxx.yyy\" cannot be used as an enum for the following reasons:\n  • the table’s primary key must not span multiple columns (id, id)\n  • the table must have exactly one primary key and optionally one comment column, not 4 columns (id, id, value, value)\n","type":"table"}

As you can see the server seems to think there are 2 id and 2 value fields but in reality there is only 1 id field and only 1 value field.

This inconsistency in the metadata (we have multiple of these messages) prevents the startup process from continuing. We currently reverted back to beta.6 where everything works just fine.

### PR DESCRIPTION
**Pull request by rakeshkky**
### Description

Avoid duplicate rows in hdb_catalog.hdb_column view if two tables with same name present in different schemas.

### Affected components 

- Server
- Tests

### Related Issues

fix #3083 

### Solution and Design

Use normal `JOIN` instead of `LEFT JOIN` for pg_class and pg_namespace tables

### CODE REVIEW

File: server/src-rsr/initialise.sql [hunk 1]
```diff
@@ -448,15 +448,22 @@ CREATE VIEW hdb_catalog.hdb_column AS
...
+LEFT JOIN
+     (
+       SELECT pg_class.oid
+            , pg_class.relname AS table_name
+            , pg_namespace.nspname AS table_schema
+         FROM pg_class
+         LEFT JOIN pg_namespace ON pg_namespace.oid = pg_class.relnamespace
+     ) table_oid ON
+       table_oid.table_name = columns.table_name
+       AND table_oid.table_schema = columns.table_schema;
```
Comment (lexi-lambda) [inline server/src-rsr/initialise.sql]: Why not just change the original `LEFT JOIN`s to ordinary (`INNER`) `JOIN`s, and move them above the `LEFT JOIN` to `primary_key_references`? That would avoid the issue with a much simpler query, and it’s not like those joins can ever fail, right?

Comment (rakeshkky) [reply server/src-rsr/initialise.sql]: Yes, That's much simpler
