### PR TITLE
actions: fix behaviour when using remote relationship in mutation action's relationship

### LINKED ISSUE #4971: remote relationship when used in action relationship gives "null: remote field selected"
Suppose `users` has a remote relationship called `auth0_profile`, if I use an action relationship to get user then `auth0_profile` resolves to "null: remote field selected". This should ideally throw a runtime error as described in: https://github.com/hasura/graphql-engine/issues/4815

image

### PR DESCRIPTION
**Pull request by codingkarthik**
fixes #4971 

### Changelog

- [x] `CHANGELOG.md` is updated with user-facing content relevant to this PR. If no changelog is required, then add the `no-changelog-required` label.

### Affected components

- [x] Server
- [ ] Console
- [ ] CLI
- [ ] Docs
- [ ] Community Content
- [ ] Build System
- [x] Tests
- [ ] Other (list it)

#### Catalog upgrade

Does this PR change Hasura Catalog version?
- [ ] No
- [ ] Yes
  - [ ] Updated docs with SQL for downgrading the catalog 

#### Metadata

Does this PR add a new Metadata feature?
- [ ] No
- [ ] Yes
  - Does `run_sql` auto manages the new metadata through schema diffing?
    - [ ] Yes
    - [ ] Not required
  - Does `run_sql` auto manages the definitions of metadata on renaming?
    - [ ] Yes
    - [ ] Not required
  - Does `export_metadata`/`replace_metadata` supports the new metadata added?
    - [ ] Yes
    - [ ] Not required

#### GraphQL
- [ ] No new GraphQL schema is generated
- [ ] New GraphQL schema is being generated:
   - [ ] New types and typenames are correlated
   
   

#### Breaking changes

- [ ] No Breaking changes
- [ ] There are breaking changes:

  1. Metadata API

     Existing `query` types:
     - [ ] Modify `args` payload which is not backward compatible
     - [ ] Behavioural change of the API
     - [ ] Change in response `JSON` schema
     - [ ] Change in error code
     

  2. GraphQL API

     Schema Generation:
     
     
     - [ ] Change in any `NamedType`
     - [ ] Change in table field names
     

     Schema Resolve:-
     
     - [ ] Change in treatment of `null` value for any input fields 
     

  3. Logging

     - [ ] Log `JSON` schema has changed
     - [ ] Log `type` names have changed

### CODE REVIEW

File: server/src-lib/Hasura/GraphQL/Resolve/Action.hs [hunk 1]
```diff
@@ -168,8 +169,16 @@ resolveActionMutationSync field executionContext sessionVariables = do
...
   let jsonAggType = mkJsonAggSelect outputType
-  return $ (,respHeaders) $ asSingleRowJsonResp (Q.fromBuilder $ toSQL $ RS.mkSQLSelect jsonAggType astResolved) []
+  return $ (,respHeaders) $
+    case remoteJoins of
+      Just remoteJoins' ->
+        let query = Q.fromBuilder $ toSQL $ RS.mkSQLSelect jsonAggType astResolved'
+        in RJ.executeQueryWithRemoteJoins manager reqHeaders userInfo query [] remoteJoins'
+      Nothing ->
+        asSingleRowJsonResp (Q.fromBuilder $ toSQL $ RS.mkSQLSelect jsonAggType astResolved) []
+
```
Comment (rakeshkky) [inline server/src-lib/Hasura/GraphQL/Resolve/Action.hs:181]: Minor naming suggestions.
`astResolved'` -> `astResolvedWithoutRemoteJoins`
`remoteJoins` -> `maybeRemoteJoins`
`remoteJoins'` -> `remoteJoins`.
