### PR TITLE
fix json/jsonb columns as String values in nested returning of a mutation (fix #3365)

### LINKED ISSUE #3365: Append Mutation Returning JSONB as String
I am finding an issue in v1.0.0-beta.10
Problem: Update mutation returns a jsonb field as string type.
The Json data is inserted into the database successfully.
Other (non json) fields in the reponse are ok.
The json field in the reponse is a proper string representation of the json and can be successfully parsed into an object with JSON.parse()

```
mutation update_something($id: Int!, $value: jsonb!) {
  update_something(where: { id: { _eq: $id } }, _append: { something_jsonb: $value }) {
    affected_rows
    returning {
      ...fields
    }
  }
}

response:
{"data":{"update_something":{"affected_rows" : 1, "returning" : [{"id":2,"something_jsonb":"{\"key1\": [{\"type\": \"id\", \"field\": \"id\", \"headerName\": \"ID\",   ...
```

### PR DESCRIPTION
**Pull request by rakeshkky**
### Description

PR #3198 caused the JSON/JSONB values returning as Strings when a mutation is performed with returning nested fields.
query:-
```graphql
mutation {
  delete_author(where: {id: {_eq: 3}}){
    affected_rows
    returning{
      id
      name
      info
      articles{
        id
        title
        content
      }
    }
  }
}
```
Response:-
```json
{
  "data": {
    "delete_author": {
      "affected_rows": 1,
      "returning": [
        {
          "id": 3,
          "name": "Author 3",
          "info": "{\"age\": 23}",
          "articles": []
        }
      ]
    }
  }
}
```
 
This PR fixes the same.

### Affected components

- [x] Server
- [ ] Console
- [ ] CLI
- [ ] Docs
- [ ] Community Content
- [ ] Build System
- [x] Tests
- [ ] Other (list it)

### Related Issues

Fix #3365 

### Solution and Design

The `parsePGScalarValue` is used to parse the Postgres column values correctly. The change in #3198 is made to select the mutated columns as Text values except for geometry/geography types. JSON/JSONB column values are parsed as JSON Strings and not as Postgres literals, which gives those values as Strings. A special `parseJSONStringAsLiteral` function is introduced, which forces all String values as Postgres literals. 

#### Catalog upgrade

Does this PR change Hasura Catalog version?
- [x] No
- [ ] Yes
  - [ ] Updated docs with SQL for downgrading the catalog 

#### Metadata

Does this PR add a new Metadata feature?
- [x] No
- [ ] Yes
  - Does `run_sql` auto manages the new metadata through schema diffing?
    - [ ] Yes
    - [ ] Not required
  - Does `run_sql` auto manages the definitions of metadata on renaming?
    - [ ] Yes
    - [ ] Not required
  - Does `export_metadata`/`replace_metadata` supports the new metadata added?
    - [ ] Yes
    - [ ] Not required

#### GraphQL
- [x] No new GraphQL schema is generated
- [ ] New GraphQL schema is being generated:
   - [ ] New types and typenames are correlated
   
   

#### Breaking changes

- [x] No Breaking changes
- [ ] There are breaking changes:

  1. Metadata API

     Existing `query` types:
     - [ ] Modify `args` payload which is not backward compatible
     - [ ] Behavioural change of the API
     - [ ] Change in response `JSON` schema
     - [ ] Change in error code
     

  2. GraphQL API

     Schema Generation:
     
     
     - [ ] Change in any `NamedType`
     - [ ] Change in table field names
     

     Schema Resolve:-
     
     - [ ] Change in treatment of `null` value for any input fields 
     

  3. Logging

     - [ ] Log `JSON` schema has changed
     - [ ] Log `type` names have changed
     

### Steps to test and verify

Reproduce #3365, the json/jsonb columns shouldn't be returned as strings.

### CODE REVIEW

File: server/src-lib/Hasura/RQL/DML/Mutation.hs [hunk 1]
```diff
@@ -90,8 +98,9 @@ mutateAndFetchCols qt cols (cte, p) strfyNum =
 
 mkSelCTEFromColVals
   :: (MonadError QErr m)
-  => QualifiedTable -> [PGColumnInfo] -> [ColVals] -> m S.CTE
-mkSelCTEFromColVals qt allCols colVals =
+  => (PGColumnType -> Value -> m (WithScalarType PGScalarValue))
+  -> QualifiedTable -> [PGColumnInfo] -> [ColVals] -> m S.CTE
+mkSelCTEFromColVals parseFn qt allCols colVals =
```
Comment (lexi-lambda) [inline server/src-lib/Hasura/RQL/DML/Mutation.hs]: Just for my own understanding: could you explain to me from a high-level what this function is doing? When I was first looking through this diff, I was slightly confused, because it seems like we’re parsing the values (using `parseFn`) but then immediately re-encoding them (using `toTxtValue`). It seems like `mutateAndSel` is doing that as part of some kind of two-pass query strategy, but it’s not quite clicking for me what the reason for doing that is.

Comment (rakeshkky) [reply server/src-lib/Hasura/RQL/DML/Mutation.hs]: To be honest, this diff is not so informative. I'll give you a bit of context. 

`toTxtValue` will encode any `PGScalarValue` to literal values. I thought it is enough and went for #3198. In case of json/jsonb values, the json string we're getting, let's say some `String t` where `t` is json string, is parsed into `PGScalarValue` as `PGValJSON (String t)`.  The `toTxtValue` converts `PGValJSON (String t)` to json encoding of a string value. The `{"age": 23}` is converted to something like `"{\"age\": 23}"`. In `mutateAndSel` function, I'm enforcing all `String t` to `PGValText t`, hence `toTxtValue` encodes correctly for json/jsonb values. 

I hope you understand the above explanation. I'm happy to know any improvements to the current fix.

Comment (lexi-lambda) [reply server/src-lib/Hasura/RQL/DML/Mutation.hs]: That definitely *is* helpful, so thank you for that explanation, but it actually doesn’t answer my original question (which is only semi-related to this pull request). Specifically, I’m trying to understand what `mkSelCTEFromColVals` is doing in the first place, from a high level. 🙂 Sorry if I didn’t make that very clear!

Comment (rakeshkky) [reply server/src-lib/Hasura/RQL/DML/Mutation.hs]: Okay :slightly_smiling_face: . The `mkSelCTEFromColVals` will generate a `SELECT` query, that is used inside a `WITH ....` statement. The `SELECT` statement look like
```sql
SELECT * FROM VALUES ((col1-val, col2-val, col3-val), .....) AS "table_name" (col1, col2, col3)
```
The `parseFn` converts JSON `value` to `col-val`.

Comment (lexi-lambda) [reply server/src-lib/Hasura/RQL/DML/Mutation.hs]: I probably should have been more clear: I can mostly make out *what* it does, but what I’m less sure about is *why*. If `mutateAndFetchCols` does the actual mutation query, and it returns a bunch of values, why don’t we parse them directly from that result? Why do we send them back through Postgres another time?

Comment (rakeshkky) [reply server/src-lib/Hasura/RQL/DML/Mutation.hs]: >  Why do we send them back through Postgres another time?

To join those values and fetch associated relationships in `returning`. Note that, this code path is executed only when relationships are selected in `returning` (See `hasNestedFld $ _mFields mut`) 

I'm happy to refactor this part of code to make it much clear and self-descriptive. :)

Comment (lexi-lambda) [reply server/src-lib/Hasura/RQL/DML/Mutation.hs]: Ahh, I see—the reason we have to do an extra `SELECT` is the information can be in related tables that aren’t actually part of the `INSERT`/`UPDATE`. Is that right?

In that case, it seems like we either (1) need to make sure our parsing logic for SQL values is round-trippable, or (2) we should avoid parsing the values we get from Postgres the first time and just store them in the textual format Postgres already knows about. Is that feasible? The approach in this PR seems a little indirect to me.

Comment (rakeshkky) [reply server/src-lib/Hasura/RQL/DML/Mutation.hs]: The (1) is possible only if we have the context of array types which #2243 is meant to solve. I think this PR is solving (2). We're fetching column values as Strings (except for geometry/geography types) and storing them as `PGValText`. The `parseJSONStringAsLiteral` is doing the job.

Comment (lexi-lambda) [reply server/src-lib/Hasura/RQL/DML/Mutation.hs]: > I think this PR is solving (2). We're fetching column values as Strings (except for geometry/geography types) and storing them as `PGValText`. The `parseJSONStringAsLiteral` is doing the job.

Okay, I think that helps me to understand better what’s going on. A followup question: why are we treating the geometry/geography types differently? They have a textual representation as well, right? So it seems as though we ought to be able to treat everything uniformly.

Comment (rakeshkky) [reply server/src-lib/Hasura/RQL/DML/Mutation.hs]: Yes, we can use the textual representation for geometry/geography columns. Ideally, the returned columns are `HashMap PGCol Text`. I'll make the necessary change in next commit.

Comment (rakeshkky) [reply server/src-lib/Hasura/RQL/DML/Mutation.hs]: Now geometry/geography values are stored as Strings via https://github.com/hasura/graphql-engine/pull/3375/commits/0f484df408336bb9827ad5bae845d98e8ce24594. Please approve if everything is OK. :slightly_smiling_face:

Comment (rakeshkky) [reply server/src-lib/Hasura/RQL/DML/Mutation.hs]: @lexi-lambda Updated the PR with the latest master. Please review. :slightly_smiling_face:
