### PR TITLE
console: fix enum tables reload data button UI (close #4647)

### LINKED ISSUE #4647: console: enum tables reload data UI is buggy
Screenshot from 2020-05-02 13-41-44

Screenshot from 2020-05-02 13-44-16

Extra details regarding remote schema is present

### PR DESCRIPTION
**Pull request by soorajshankar**
### Description

Enum table reload button UI was buggy, fixed styling, and rendering logic. 

### Changelog

- [x] `CHANGELOG.md` is updated with user-facing content relevant to this PR.

### Affected components

- [ ] Server
- [x] Console
- [ ] CLI
- [ ] Docs
- [ ] Community Content
- [ ] Build System
- [ ] Tests
- [ ] Other (list it)

### Related Issues

close #4647

### Solution and Design

- `Reload all remote schemas` checkbox is removed from the Data module.
- Checkbox functionality was not working which is fixed in this PR.
- Metadata modules will have reload button and the checkbox.

### Steps to test and verify

- Go to the data module and open an enum table.
- match the UI in browse tab
image
- match UI in the insert tab
image
- match the UI from settings
image

#### Catalog upgrade

Does this PR change Hasura Catalog version?
- [x] No
- [ ] Yes
  - [ ] Updated docs with SQL for downgrading the catalog 

#### Metadata

Does this PR add a new Metadata feature?
- [x] No
- [ ] Yes
  - Does `run_sql` auto manages the new metadata through schema diffing?
    - [ ] Yes
    - [ ] Not required
  - Does `run_sql` auto manages the definitions of metadata on renaming?
    - [ ] Yes
    - [ ] Not required
  - Does `export_metadata`/`replace_metadata` supports the new metadata added?
    - [ ] Yes
    - [ ] Not required

#### GraphQL
- [x] No new GraphQL schema is generated
- [ ] New GraphQL schema is being generated:
   - [ ] New types and typenames are correlated
   
   

#### Breaking changes

- [x] No Breaking changes
- [ ] There are breaking changes:

  1. Metadata API

     Existing `query` types:
     - [ ] Modify `args` payload which is not backward compatible
     - [ ] Behavioural change of the API
     - [ ] Change in response `JSON` schema
     - [ ] Change in error code
     

  2. GraphQL API

     Schema Generation:
     
     
     - [ ] Change in any `NamedType`
     - [ ] Change in table field names
     

     Schema Resolve:-
     
     - [ ] Change in treatment of `null` value for any input fields 
     

  3. Logging

     - [ ] Log `JSON` schema has changed
     - [ ] Log `type` names have changed

### CODE REVIEW

File: console/src/components/Services/Data/Common/Components/ReloadEnumValuesButton.js [hunk 1]
```diff
@@ -1,32 +1,17 @@
...
-    <Tooltip id="tooltip-reload-enum-metadata">
-      Reload enum values in your GraphQL schema after inserting, updating or
-      deleting enum values
-    </Tooltip>
+const ReloadEnumValuesButton = ({ isEnum, dispatch }) =>
+  isEnum && (
+    <ReloadMetadata
+      buttonText="Reload enum values"
+      buttonToolTip={TOOLTIP_TEXT}
+      checkBoxVisible={false}
```
Comment (beerose) [inline console/src/components/Services/Data/Common/Components/ReloadEnumValuesButton.js:12]: Someone's first thought might be _What checkbox?_ Let's make it more descriptive. 

Couple suggestions:
- `showReloadRemoteSchemas`
- `canReloadRemoteSchemas`
- `reloadRemoteSchemasButton`
