### PR TITLE
console: fix inconsistency in permissions builder (close #4119)

### LINKED ISSUE #4119: Permission builder UI: Inconsistency in specifying table name using the _exists operator
exists_table_name

The key for mentioning table name in the json is "name" and in the json creator is "table"

### PR DESCRIPTION
**Pull request by Varun-Choudhary**
closes #4119 
 
### Description

This PR fixes certain typo's on `PermissionBuilder.js' and 'Permission.js'.

### Affected components

- [x] Console

### CODE REVIEW

File: console/src/components/Services/Data/TablePermissions/Permissions.js [hunk 1]
```diff
@@ -1667,7 +1667,7 @@ class Permissions extends Component {
 
             return (
               <div key={index} className={styles.add_mar_bottom_mid}>
-                {getSelect('table', tableOptions, permissionsState.table)}
+                {getSelect('name', tableOptions, permissionsState.table)}
```
Comment (beerose) [inline console/src/components/Services/Data/TablePermissions/Permissions.js:1670]: Why was this change also needed?

Comment (Varun-Choudhary) [reply console/src/components/Services/Data/TablePermissions/Permissions.js]: Yeah. It's not required.

Comment (Varun-Choudhary) [reply console/src/components/Services/Data/TablePermissions/Permissions.js]: Update the change
