### PR TITLE
action relationship page improvements (fix #4062, #4130)

### LINKED ISSUE #4062: console: allow editing action relationship names
### Problem
Whenever I rename the relationship within the `Actions -> [actionName] -> Relationships` tab, a new relationship is inserted instead of updating the old relationship.

### Steps to Reproduce
1. Go to "Actions" in the console
2. Click on an existing action from the left-hand menu
3. Click on the "Relationships" tab
4. Click "Edit" on an existing relationship
5. Change the name of the relationship and hit "Save"
6. A new relationship is created instead of updating the initial relationship.

### Version
graphql-engine:v1.2.0-beta.2

P.S.: thank you all so much for building this amazing feature - it's going to simplify our architecture immensely!

### PR DESCRIPTION
**Pull request by wawhal**
### Description

- Allow renaming relationships from the console elegantly
- Include the action's output type name in the relationship definition so that it is clear that the relationship is a property of a type and not an action

### Changelog

- [x] `CHANGELOG.md` is updated with user-facing content relevant to this PR.

### Affected components

- [ ] Server
- [x] Console
- [ ] CLI
- [ ] Docs
- [ ] Community Content
- [ ] Build System
- [ ] Tests
- [ ] Other (list it)

### Related Issues

#4062 #4130

### CODE REVIEW

File: console/src/components/Services/Actions/Relationships/utils.js [hunk 1]
```diff
@@ -90,3 +90,15 @@ export const removeTypeRelationship = (types, typename, relName) => {
     return t;
   });
 };
+
+export const validateRelTypename = (types, typename, relname) => {
+  for (let i = types.length - 1; i >= 0; i--) {
+    const type = types[i];
+    if (type.kind === 'object' && type.name === typename) {
+      if ((type.relationships || []).find(r => r.name === relname)) {
```
Comment (beerose) [inline console/src/components/Services/Actions/Relationships/utils.js]: Since you just want a boolean and don't care about the result of `find` what about using `some` here?
