### PR TITLE
auto-include `__typename` field in custom types' objects (fix #4063)

### LINKED ISSUE #4063: allow '__typename' in action output type
Via `macs#0170` on Discord

The return type of an action does not contain `__typename `(needed by apollo client).. So when I try to do an action mutation I get this error:

```json
{
  "errors": [
    {
      "extensions": {
        "path": "$.selectionSet.move_task.selectionSet.__typename",
        "code": "validation-failed"
      },
      "message": "field \"__typename\" not found in type: 'task_move_response'"
    }
  ]
}
```

### PR DESCRIPTION
**Pull request by rakeshkky**
### Description

Selecting `__typename` field in objects of custom types for actions results in validation error. This PR fixes the same.

### Changelog

- [x] `CHANGELOG.md` is updated with user-facing content relevant to this PR.

### Affected components

- [x] Server
- [ ] Console
- [ ] CLI
- [ ] Docs
- [ ] Community Content
- [ ] Build System
- [x] Tests
- [ ] Other (list it)

### Related Issues

Fix #4063 

### Solution and Design

Use `mkObjTyInfo` function to construct the `ObjTyInfo` for the custom types. The function auto-includes the `__typename` field.

### Steps to test and verify

Perform an action by including `__typename` in the selection set.

#### Catalog upgrade

Does this PR change Hasura Catalog version?
- [x] No
- [ ] Yes

#### Metadata

Does this PR add a new Metadata feature?
- [x] No
- [ ] Yes

#### GraphQL
- [x] No new GraphQL schema is generated
- [ ] New GraphQL schema is being generated:

#### Breaking changes

- [x] No Breaking changes
- [ ] There are breaking changes

### CODE REVIEW

File: server/src-lib/Hasura/GraphQL/RemoteServer.hs [hunk 1]
```diff
@@ -159,43 +158,10 @@ mergeQueryRoot :: GS.GCtx -> GS.GCtx -> VT.ObjTyInfo
...
-  in bool (Just merged) Nothing $ merged == mempty
-  where
-    newRootOrEmpty x y =
-      if x == mempty && y /= mempty
-      then mkNewEmptyMutRoot
-      else x
-
-mkNewEmptyMutRoot :: VT.ObjTyInfo
-mkNewEmptyMutRoot = VT.ObjTyInfo (Just "mutation root")
-                    (G.NamedType "mutation_root") Set.empty Map.empty
```
Comment (rakeshkky) [inline server/src-lib/Hasura/GraphQL/RemoteServer.hs]: `Maybe a` has [Semigroup instance](http://hackage.haskell.org/package/base-4.12.0.0/docs/src/GHC.Base.html#line-403). So, `<>` can be directly used to merge `Maybe mutationRoot`s here. No need for `mkNewEmptyMutRoot`.

File: server/src-lib/Hasura/GraphQL/RemoteServer.hs [hunk 2]
```diff
@@ -159,43 +158,10 @@ mergeQueryRoot :: GS.GCtx -> GS.GCtx -> VT.ObjTyInfo
...
-  in bool (Just merged) Nothing $ merged == mempty
-  where
-    newRootOrEmpty x y =
-      if x == mempty && y /= mempty
-      then mkNewEmptySubRoot
-      else x
-
-mkNewEmptySubRoot :: VT.ObjTyInfo
-mkNewEmptySubRoot = VT.ObjTyInfo (Just "subscription root")
-                    (G.NamedType "subscription_root") Set.empty Map.empty
```
Comment (rakeshkky) [inline server/src-lib/Hasura/GraphQL/RemoteServer.hs]: The explanation in above comment applicable here for subscription roots.

File: server/src-lib/Hasura/GraphQL/Resolve/Action.hs [hunk 3]
```diff
@@ -210,7 +210,7 @@ resolveAsyncActionQuery userInfo selectOpCtx field = do
 
   annotatedFields <- fmap (map (first FieldName)) $ withSelSet (_fSelSet field) $ \fld ->
     case _fName fld of
-      "__typename" -> return $ RS.FExp $ G.unName $ G.unNamedType $ _fType fld
+      "__typename" -> return $ RS.FExp $ G.unName $ G.unNamedType $ _fType field
       "output"     -> do
```
Comment (rakeshkky) [inline server/src-lib/Hasura/GraphQL/Resolve/Action.hs]: Using `fld` type here is a bug which always results in `String` for `__typename` field.
