### PR TITLE
Fix JSON(B) rendering in data browser (close #4201)

### LINKED ISSUE #4201: JSONB fields aren't presented adequately
JSON of Schrodinger:

Screen Shot 2020-03-26 at 11 05 37

One is a string (by mistake) and the other one is an object. Which one is the correct one?

Screen Shot 2020-03-26 at 11 05 46

Screen Shot 2020-03-26 at 11 05 55

You figure when you edit the row.

What you guys think about showing in the listing as it is shown in the edit?

I can make a PR if you agree.

### PR DESCRIPTION
**Pull request by sobrinho**
### Description

Hasura was rendering strings and objects as the same in browse rows, we couldn't differentiate one from another.

### Changelog

- [ ] `CHANGELOG.md` is updated with user-facing content relevant to this PR.

### Affected components

- [ ] Server
- [x] Console
- [ ] CLI
- [ ] Docs
- [ ] Community Content
- [ ] Build System
- [ ] Tests
- [ ] Other (list it)

### Related Issues

#4201

### Solution and Design

Checking if the column is a JSON or JSONB type instead of only if the value is an object fix the issue.

Before (You couldn't tell that one of the rows is a string by mistake):

Screen Shot 2020-03-28 at 18 41 24

After (You can see the difference clearly):

Screen Shot 2020-03-28 at 18 37 46

### Steps to test and verify

Create one json and one jsonb columns, create two rows, one with both values as `{"object":true}` and another one with both values as `"{\"string\": \"true\"}"`.

You can't tell the difference in `Browse Rows` before and you should after this fix.

### Limitations, known bugs & workarounds

None.

### Server checklist

None.

#### Catalog upgrade

Does this PR change Hasura Catalog version?
- [x] No
- [ ] Yes
  - [ ] Updated docs with SQL for downgrading the catalog 

#### Metadata

Does this PR add a new Metadata feature?
- [x] No
- [ ] Yes
  - Does `run_sql` auto manages the new metadata through schema diffing?
    - [ ] Yes
    - [ ] Not required
  - Does `run_sql` auto manages the definitions of metadata on renaming?
    - [ ] Yes
    - [ ] Not required
  - Does `export_metadata`/`replace_metadata` supports the new metadata added?
    - [ ] Yes
    - [ ] Not required

#### GraphQL
- [x] No new GraphQL schema is generated
- [ ] New GraphQL schema is being generated:
   - [ ] New types and typenames are correlated
   
   

#### Breaking changes

- [x] No Breaking changes
- [ ] There are breaking changes:

  1. Metadata API

     Existing `query` types:
     - [ ] Modify `args` payload which is not backward compatible
     - [ ] Behavioural change of the API
     - [ ] Change in response `JSON` schema
     - [ ] Change in error code
     

  2. GraphQL API

     Schema Generation:
     
     
     - [ ] Change in any `NamedType`
     - [ ] Change in table field names
     

     Schema Resolve:-
     
     - [ ] Change in treatment of `null` value for any input fields 
     

  3. Logging

     - [ ] Log `JSON` schema has changed
     - [ ] Log `type` names have changed

### CODE REVIEW

File: console/src/components/Services/Data/TableBrowseRows/ViewRows.js [hunk 1]
```diff
@@ -759,9 +763,7 @@ const ViewRows = ({
           <b className={styles.padd_small_right}>Selected:</b>
           {selectedRows.length}
           <button
-            className={`${styles.add_mar_right_small} btn btn-xs btn-default ${
-              styles.bulkDeleteButton
-            }`}
+            className={`${styles.add_mar_right_small} btn btn-xs btn-default ${styles.bulkDeleteButton}`}
```
Comment (sobrinho) [inline console/src/components/Services/Data/TableBrowseRows/ViewRows.js]: This was done by the linter, not me.

Comment (beerose) [reply console/src/components/Services/Data/TableBrowseRows/ViewRows.js]: Yup, this is proper formatting. It was wrongly formatted on the master.
