### PR TITLE
fix introspection faling when multiple actions defined with PG scalar types (fix #5166)

### LINKED ISSUE #5166: Actions causing introspection to break
Hasura: v1.3.0-beta.2 (possibly before as well)

Reported in: https://app.intercom.com/a/apps/rucirpb3/inbox/inbox/mentions/conversations/61371600000816

Suppose I have two actions and my hasura metadata is:

```
{
  "version": 2,
  "tables": [],
  "actions": [
    {
      "name": "actionName",
      "definition": {
        "handler": "http://localhost:3000",
        "output_type": "SampleOutput",
        "arguments": [
          {
            "name": "text",
            "type": "jsonb!"
          },
          {
            "name": "attributes",
            "type": "String!"
          }
        ],
        "type": "mutation",
        "kind": "synchronous"
      }
    },
    {
      "name": "actionName2",
      "definition": {
        "handler": "http://localhost:3000",
        "output_type": "SampleOutput2",
        "arguments": [
          {
            "name": "a",
            "type": "ID!"
          },
          {
            "name": "b",
            "type": "ID!"
          }
        ],
        "type": "mutation",
        "kind": "synchronous"
      }
    }
  ],
  "custom_types": {
    "input_objects": [
      {
        "name": "SampleInput",
        "fields": [
          {
            "name": "username",
            "type": "String!"
          },
          {
            "name": "password",
            "type": "String!"
          }
        ]
      }
    ],
    "objects": [
      {
        "name": "SampleOutput",
        "fields": [
          {
            "name": "id",
            "type": "String!"
          }
        ]
      },
      {
        "name": "SampleOutput2",
        "fields": [
          {
            "name": "id",
            "type": "String!"
          }
        ]
      }
    ]
  }
}
```

This breaks introspection with error: `{"errors":[{"extensions":{"path":"$","code":"unexpected"},"message":"type info not found for: 'jsonb'"}]}`

### PR DESCRIPTION
**Pull request by rakeshkky**
### Description

Introspection query is failing with `type info not found for xxxx` error message if multiple actions are defined with reused PG scalars. The PR fixes the same.

### Changelog

- [x] `CHANGELOG.md` is updated with user-facing content relevant to this PR. If no changelog is required, then add the `no-changelog-required` label.

### Affected components

- [x] Server
- [x] Tests

### Related Issues

Fix #5166 

### Solution and Design

See the in line diff [comment](https://github.com/hasura/graphql-engine/pull/5173#discussion_r443657562). 

### Steps to test and verify

Define more than one actions with PG scalars. The introspection query should go through and schema should be shown in the graphiql docs.

### Limitations, known bugs & workarounds

NA

#### Catalog upgrade

Does this PR change Hasura Catalog version?
- [x] No
- [ ] Yes

#### Metadata

Does this PR add a new Metadata feature?
- [x] No
- [ ] Yes

#### GraphQL
- [x] No new GraphQL schema is generated
- [ ] New GraphQL schema is being generated

#### Breaking changes

- [x] No Breaking changes
- [ ] There are breaking changes

### CODE REVIEW

File: server/src-lib/Hasura/GraphQL/Schema/Action.hs [hunk 1]
```diff
@@ -337,43 +336,47 @@ mkActionsSchema =
...
   mempty
   where
     -- we'll need to add uuid and timestamptz for actions
-    mkNewRoleState pgScalars =
+    initRoleState =
       ( mempty
-      , foldr addScalarToTyAgg mempty $
-        pgScalars <> Set.fromList [PGJSON, PGTimeStampTZ, PGUUID]
+      , foldr addScalarToTyAgg mempty [PGJSON, PGTimeStampTZ, PGUUID]
       )
```
Comment (rakeshkky) [inline server/src-lib/Hasura/GraphQL/Schema/Action.hs:351]: This function is causing the issue. The `mkNewRoleState` function initiates the state with empty `RootFields` and `TyAgg` with PG scalars reused and mandatory scalars for actions.This function is invoked only for the first action in the list (unfortunately) and remaining actions' reused PG scalars were not added. Hence the issue only exist if multiple actions are defined. The fix is to move adding PG scalars here to the accumulate functions where the PG scalars are added to `TyAgg` explicitly for each action.
