### PR TITLE
fix intermittent errors occur when query actions used with variables

### LINKED ISSUE #4520: do not cache plan for action queries
From [Discord](https://discordapp.com/channels/407792526867693568/516590536875048990/701909454811037738):

```
I get intermittent validation errors on the variables:
"path":"$.variableValues","error":"unexpected variables: ticker","code":"validation-failed"

it works on and off so it's really hard to understand what's going on. It's a simple query with just one string variable. It works well without variables

Any ideas?
```

@rakeshkky said

```
These action queries, we are marking them as re-usable without capturing the variable value in the state as re-usable variables. This is because we ain't using the input arguments in action query field for generating the SQL statement, instead we are converting them to JSON and including it in action webhook POST request payload. The fix is, by design, we shouldn't cache action queries.
```

### PR DESCRIPTION
**Pull request by codingkarthik**
fixes #4520 

### Description

A query action when used with variables used to give intermittent errors when executed multiple times. This PR fixes the bug by not adding the query action to the plan cache.

### Changelog

- [ ] `CHANGELOG.md` is updated with user-facing content relevant to this PR.

### Affected components

- [x] Server
- [ ] Console
- [ ] CLI
- [ ] Docs
- [ ] Community Content
- [ ] Build System
- [x] Tests
- [ ] Other (list it)

#### Catalog upgrade

Does this PR change Hasura Catalog version?
- [x] No
- [ ] Yes
  - [ ] Updated docs with SQL for downgrading the catalog 

#### Metadata

Does this PR add a new Metadata feature?
- [x] No
- [ ] Yes
  - Does `run_sql` auto manages the new metadata through schema diffing?
    - [ ] Yes
    - [ ] Not required
  - Does `run_sql` auto manages the definitions of metadata on renaming?
    - [ ] Yes
    - [ ] Not required
  - Does `export_metadata`/`replace_metadata` supports the new metadata added?
    - [ ] Yes
    - [ ] Not required

#### GraphQL
- [x] No new GraphQL schema is generated
- [ ] New GraphQL schema is being generated:
   - [ ] New types and typenames are correlated
   
   

#### Breaking changes

- [x] No Breaking changes
- [ ] There are breaking changes:

  1. Metadata API

     Existing `query` types:
     - [ ] Modify `args` payload which is not backward compatible
     - [ ] Behavioural change of the API
     - [ ] Change in response `JSON` schema
     - [ ] Change in error code
     

  2. GraphQL API

     Schema Generation:
     
     
     - [ ] Change in any `NamedType`
     - [ ] Change in table field names
     

     Schema Resolve:-
     
     - [ ] Change in treatment of `null` value for any input fields 
     

  3. Logging

     - [ ] Log `JSON` schema has changed
     - [ ] Log `type` names have changed

### CODE REVIEW

File: server/src-lib/Hasura/GraphQL/Resolve.hs [hunk 1]
```diff
@@ -119,13 +119,19 @@ queryFldToPGAST fld actionExecuter = do
...
+      -- an SQL query, but in case of query actions it's converted into JSON
+      -- and included in the action's webhook payload.
+      markNotReusable
+      f <$> actionExecuter (RA.resolveActionQuery fld ctx (userVars userInfo))
       where
         outputType = _saecOutputType ctx
         jsonAggType = RA.mkJsonAggSelect outputType
+        f = case jsonAggType of
+             DS.JASMultipleRows -> QRFActionExecuteList
+             DS.JASSingleObject -> QRFActionExecuteObject
```
Comment (rakeshkky) [inline server/src-lib/Hasura/GraphQL/Resolve.hs:134]: Move this to function body under `let`. The `f` is ambiguous and it is more readable if it is used as soon as declared.

Comment (codingkarthik) [reply server/src-lib/Hasura/GraphQL/Resolve.hs:134]: I thought it would be better to have all the bindings under `where`. I'll make the change
