### PR TITLE
sql queries refactor (closes #3543)

### LINKED ISSUE #3543: missing semi-colon in create table down migration
I squashed my migrations and ended up with a `down.sql` file that looks like:

```
DROP TABLE "public"."todos"
DROP TABLE "public"."users"
```

There is no semi-colon after the statements and so when running the down migration, I get the following error:

```
FATA[0000] apply failed: [postgres-error] query execution failed ($.args[58].args)
File: '1576429237138_init/down.sql'
{
    "sql": "\nDROP TABLE \"public\".\"todos\"\nDROP TABLE \"public\".\"users\"\n"
}
[42601] FatalError: syntax error at or near "DROP" 
```

Terminating the statements with a semi-colon fixes the problem for me.

### PR DESCRIPTION
**Pull request by wawhal**
### Description

Fixes semicolon inconsistencies in SQL.
Minor refactor to use a single function for all `run_sql` queries

### Affected components

- [ ] Server
- [x] Console
- [ ] CLI
- [ ] Docs
- [ ] Community Content
- [ ] Build System
- [ ] Tests
- [ ] Other (list it)

### Related Issues

#3543

#### Catalog upgrade

Does this PR change Hasura Catalog version?
- [ ] No
- [ ] Yes
  - [ ] Updated docs with SQL for downgrading the catalog 

#### Metadata

Does this PR add a new Metadata feature?
- [ ] No
- [ ] Yes
  - Does `run_sql` auto manages the new metadata through schema diffing?
    - [ ] Yes
    - [ ] Not required
  - Does `run_sql` auto manages the definitions of metadata on renaming?
    - [ ] Yes
    - [ ] Not required
  - Does `export_metadata`/`replace_metadata` supports the new metadata added?
    - [ ] Yes
    - [ ] Not required

#### GraphQL
- [ ] No new GraphQL schema is generated
- [ ] New GraphQL schema is being generated:
   - [ ] New types and typenames are correlated
   
   

#### Breaking changes

- [ ] No Breaking changes
- [ ] There are breaking changes:

  1. Metadata API

     Existing `query` types:
     - [ ] Modify `args` payload which is not backward compatible
     - [ ] Behavioural change of the API
     - [ ] Change in response `JSON` schema
     - [ ] Change in error code
     

  2. GraphQL API

     Schema Generation:
     
     
     - [ ] Change in any `NamedType`
     - [ ] Change in table field names
     

     Schema Resolve:-
     
     - [ ] Change in treatment of `null` value for any input fields 
     

  3. Logging

     - [ ] Log `JSON` schema has changed
     - [ ] Log `type` names have changed

### CODE REVIEW

File: console/src/components/Common/utils/v1QueryUtils.js [hunk 1]
```diff
@@ -50,3 +51,29 @@ export const getSetCustomRootFieldsQuery = (
     },
   };
 };
+
+export const getSetTableEnumQUery = (tableDef, isEnum) => {
```
Comment (rikinsk) [inline console/src/components/Common/utils/v1QueryUtils.js]: QUery -> Query

File: console/src/components/Common/utils/v1QueryUtils.js [hunk 2]
```diff
@@ -1,8 +1,9 @@
 export const getRunSqlQuery = (sql, shouldCascade, readOnly) => {
+  const sqlWithSemicolon = sql[sql.length - 1] !== ';' ? sql + ';' : sql;
```
Comment (rikinsk) [inline console/src/components/Common/utils/v1QueryUtils.js]: We can move this to sqlutils as a function `terminateSql`. You also need to trim the sql first.
