### PR TITLE
cli: fix error on seed create command

### LINKED ISSUE #5532: FATA[0000] exporting seed data: [unexpected] error while executing pg_dump: pg_dump: error: no matching tables were found  ($)
I get this error with tables, that contains capital letters(table name). I don't have any problem with tables, that contains only lowercase letters.

### PR DESCRIPTION
**Pull request by kolharsam**
fixes #5532 

### Description

Fixes an issue while using the seed migrations with tables that have capital letters in them.

### Affected components

- [x] CLI

### CODE REVIEW

File: cli/migrate/migrate.go [hunk 1]
```diff
@@ -1847,7 +1847,12 @@ func (m *Migrate) ApplySeed(q interface{}) error {
 }
 
 func (m *Migrate) ExportDataDump(tableNames []string) ([]byte, error) {
-	return m.databaseDrv.ExportDataDump(tableNames)
+	// to support tables starting with capital letters
+	modifiedTableNames := make([]string, len(tableNames))
+	for idx, val := range tableNames {
+		modifiedTableNames[idx] = "\"" + val + "\""
```
Comment (scriptonist) [inline cli/migrate/migrate.go:1853]: May be a bit pedantic, but can we change this to ?
```suggestion
		modifiedTableNames[idx] = fmt.Sprintf(`"%s"`, val) 
```
