### PR TITLE
console: fix primary key selector bug and raw sql error message (close #4226)

### LINKED ISSUE #4226: deleting a column with the edit primary key section open crashes the console
Steps to reproduce:
- Create a table with a column `id` that is the primary key
- Save the table
- Modify the table and add a new column `id2`
- Set `id2` as the new primary key
- Delete the column `id`
- _Console crashes_
- Refreshing with F5 brings the console back, the operation was successful
- Rename the column `id2` to `id`

I did this cause I had to change the default value of `id`. Might not be the intended way to do this, but it crashes the console, so it might be relevant. Tested on the latest Heroku build. That's the output:

```n/<@https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v1.1/main.js.gz:1:1777043
n@https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v1.1/main.js.gz:1:1776005
n@https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v1.1/main.js.gz:1:1777237
ho@https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v1.1/vendor.js.gz:1:2735575
Wo@https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v1.1/vendor.js.gz:1:2742531
Xo@https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v1.1/vendor.js.gz:1:2748881
fs@https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v1.1/vendor.js.gz:1:2771410
ds@https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v1.1/vendor.js.gz:1:2771798
Js@https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v1.1/vendor.js.gz:1:2778976
Ys@https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v1.1/vendor.js.gz:1:2778346
Ws@https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v1.1/vendor.js.gz:1:2777351
bs@https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v1.1/vendor.js.gz:1:2776151
enqueueSetState@https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v1.1/vendor.js.gz:1:2727016
k.prototype.setState@https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v1.1/vendor.js.gz:1:2673963
e@https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v1.1/vendor.js.gz:1:97329
r@https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v1.1/vendor.js.gz:1:93325
e@https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v1.1/vendor.js.gz:1:93795
e@https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v1.1/vendor.js.gz:1:97234
g@https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v1.1/vendor.js.gz:1:456432
R/</<@https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v1.1/main.js.gz:1:4343947
o/</</<@https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v1.1/vendor.js.gz:1:2818608
n/</</<@https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v1.1/vendor.js.gz:1:2393731
e@https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v1.1/vendor.js.gz:1:461470
n/</<@https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v1.1/main.js.gz:1:72024```

### PR DESCRIPTION
**Pull request by Varun-Choudhary**
fixes #4226 

### Description

Updates the required redux state upon deletion of a column. This should fix the error that is described #4226

### Changelog

- [x] `CHANGELOG.md` is updated with user-facing content relevant to this PR. If no changelog is required, then add the `no-changelog-required` label.

### Affected components

- [x] Console

### Solution and Design

Modifying primary-Key Column index while deleting a column.

### Steps to test and verify

 - go to #4226 and perform the steps mentioned. 
 - upon deletion of certain column(s), we shouldn't be hitting the `404` page.

### CODE REVIEW

File: console/src/components/Services/Data/TableModify/ColumnEditorList.js [hunk 1]
```diff
@@ -104,6 +105,31 @@ const ColumnEditorList = ({
...
+                pk.push(index2 - 1);
+              }
+            }
+          }
+          flag = true;
+        }
+        const pks = [];
+        for (const [_, value1] of pk.sort().entries()) {
+          pks.push(value1.toString());
+        }
```
Comment (kolharsam) [inline console/src/components/Services/Data/TableModify/ColumnEditorList.js:130]: You could do a similar operation like so : 
```suggestion
       const pks = [...pk.sort()];
```

Comment (kolharsam) [reply console/src/components/Services/Data/TableModify/ColumnEditorList.js:130]: Also, I wanted to understand why `.sort()` is required?

File: console/src/components/Services/Data/TableModify/ColumnEditorList.js [hunk 2]
```diff
@@ -104,6 +105,31 @@ const ColumnEditorList = ({
 
       const isOk = getConfirmation(confirmMessage, true, colName);
       if (isOk) {
+        const pk = [];
+        let flag = true;
+        for (const [_, value1] of tableSchema.primary_key.columns.entries()) {
+          for (const [index2, value2] of tableSchema.columns.entries()) {
+            if (value2.column_name.localeCompare(colName) == 0) {
```
Comment (kolharsam) [inline console/src/components/Services/Data/TableModify/ColumnEditorList.js:112]: 2 Notes here:
 - Preferrable to use `===` over `==`
 - the whole conditional can be replaced with `if (!value2.column_name.localeCompare(colName))`, since `0` is a `falsy` value. (Read more here: https://developer.mozilla.org/en-US/docs/Glossary/Falsy)

File: console/src/components/Services/Data/TableModify/ColumnEditorList.js [hunk 3]
```diff
@@ -104,6 +105,31 @@ const ColumnEditorList = ({
 
       const isOk = getConfirmation(confirmMessage, true, colName);
       if (isOk) {
+        const pk = [];
+        let flag = true;
+        for (const [_, value1] of tableSchema.primary_key.columns.entries()) {
+          for (const [index2, value2] of tableSchema.columns.entries()) {
```
Comment (kolharsam) [inline console/src/components/Services/Data/TableModify/ColumnEditorList.js:111]: Could you try and do the same with `.forEach` since we're using to array's here?

Comment (Varun-Choudhary) [reply console/src/components/Services/Data/TableModify/ColumnEditorList.js:111]: Yeah. I will try doing with .forEach

File: console/src/components/Services/Data/TableModify/ColumnEditorList.js (hunk 2 above)
Comment (Varun-Choudhary) [reply console/src/components/Services/Data/TableModify/ColumnEditorList.js:112]: Okay

File: console/src/components/Services/Data/TableModify/ColumnEditorList.js [hunk 4]
```diff
@@ -1,3 +1,4 @@
+/*eslint no-unused-vars: 0*/
```
[the remark this answers is not in the document]
Comment (Varun-Choudhary) [reply console/src/components/Services/Data/TableModify/ColumnEditorList.js:1]: Okay

File: console/src/components/Services/Data/TableModify/ColumnEditorList.js [hunk 5]
```diff
@@ -104,10 +104,29 @@ const ColumnEditorList = ({
 
       const isOk = getConfirmation(confirmMessage, true, colName);
       if (isOk) {
+        const pk = [];
+        let flag = true;
```
Comment (kolharsam) [inline console/src/components/Services/Data/TableModify/ColumnEditorList.js:108]: You could perhaps change the name of this variable. Maybe something like `pkPresentFlag`? Also, adding a comment in the above line which would help others know why that flag variable is necessary would be awesome!

Comment (Varun-Choudhary) [reply console/src/components/Services/Data/TableModify/ColumnEditorList.js:108]: Yeah. Will do the changes.

File: console/src/components/Services/Data/TableModify/ColumnEditorList.js [hunk 6]
```diff
@@ -104,10 +104,29 @@ const ColumnEditorList = ({
...
+        tableSchema.primary_key.columns.forEach(pkCol => {
+          const currentPKCol = pkCol;
+          tableSchema.columns.forEach((nonPKCol, colIndex) => {
+            if (!nonPKCol.column_name.localeCompare(colName)) {
```
[the remark this answers is not in the document]
Comment (Varun-Choudhary) [reply console/src/components/Services/Data/TableModify/ColumnEditorList.js:112]: Cool

File: CHANGELOG.md [hunk 7]
```diff
@@ -6,6 +6,7 @@
 
 (Add entries here in the order of: server, console, cli, docs, others)
 
+- server: add request/response sizes in event triggers (and scheduled trigger) logs
```
Comment (beerose) [inline CHANGELOG.md:9]:
```suggestion
```

File: console/src/components/Services/Data/TableModify/PrimaryKeyEditor.js [hunk 8]
```diff
@@ -1,4 +1,4 @@
-import React from 'react';
+import React, { useState } from 'react';
```
Comment (beerose) [inline console/src/components/Services/Data/TableModify/PrimaryKeyEditor.js:1]:
```suggestion
import React, { useEffect } from 'react';
```
