### PR TITLE
server: multiple subscriptions && `_st_d_within` in subscriptions (fix #3239)

### LINKED ISSUE #3239: "postgres query error" when using subscriptions and "_st_d_within" expression to compare columns of type geography
I tested postgis extension and `_st_d_within` expressions and noticed following bug.

First of all I have a table called messages and one of the columns is called location (type geography). I created following query:
```
query GetMessages($point: geography!, $distance: Float!) {
  messages(where: {location: {_st_d_within: {distance: $distance, from: $point}}}) {
    id
    location
    message
    createdAt
  }
}
```
and used following variables:
```
{
  "point": {
    "type": "Point",
    "coordinates": [ 52.2, 40.2 ]
  },
  "distance": 20.0
}
```
Everything works as expected, I get messages within the radius defined in variables.

If I change the same query to subscription:
```
subscription GetMessages($point: geography!, $distance: Float!) {
  messages(where: {location: {_st_d_within: {distance: $distance, from: $point}}}) {
    id
    location
    message
    createdAt
  }
}
```
and use same variables I get following error on graphiql:
```
{
  "data": null,
  "errors": [
    {
      "errors": [
        {
          "extensions": {
            "path": "$",
            "code": "unexpected"
          },
          "message": "postgres query error"
        }
      ]
    }
  ]
}
```
I also checked out the postgres logs and found out following error message:
```
postgres_1        | 2019-10-25 17:47:04.581 UTC [4773] ERROR:  parse error - invalid geometry
postgres_1        | 2019-10-25 17:47:04.581 UTC [4773] HINT:  "{"" <-- parse error at position 2 within geometry
postgres_1        | 2019-10-25 17:47:04.581 UTC [4773] STATEMENT:
postgres_1        | 	        select
postgres_1        | 	          _subs.result_id, _fld_resp.root as result
postgres_1        | 	          from
postgres_1        | 	            unnest(
postgres_1        | 	              $1::uuid[], $2::json[]
postgres_1        | 	            ) _subs (result_id, result_vars)
postgres_1        | 	          left outer join lateral
postgres_1        | 	            (
postgres_1        | 	        SELECT  coalesce(json_agg("root" ), '[]' ) AS "root" FROM  (SELECT  row_to_json((SELECT  "_4_e"  FROM  (SELECT  "_0_root.base"."id" AS "id", (ST_AsGeoJSON("_0_root.base"."location", 15, 4 ))::json AS "location", "_0_root.base"."message" AS "message", "_0_root.base"."createdAt" AS "createdAt", "_3_root.ar.root.comments_aggregate"."comments_aggregate" AS "comments_aggregate"       ) AS "_4_e"      ) ) AS "root" FROM  (SELECT  *  FROM "public"."messages"  WHERE ((ST_DWithin("public"."messages"."location", (("_subs"."result_vars"#>>ARRAY['query', 'point']))::geography, (("_subs"."result_vars"#>>ARRAY['query', 'distance']))::real, (("_subs"."result_vars"#>>ARRAY['synthetic', '0']))::boolean )))     ) AS "_0_root.base" LEFT OUTER JOIN LATERAL (SELECT  json_build_object('aggregate', json_build_object('count', COUNT(*) ) ) AS "comments_aggregate" FROM  (SELECT  1 AS "root.ar.root.comments_aggregate__one" FROM  (SELECT  *  FROM "public"."comment"  WHERE (("_0_root.base"."id") = ("messageId"))     ) AS "_1_root.ar.root.comments_aggregate.base"      ) AS "_2_root.ar.root.comments_aggregate"      ) AS "_3_root.ar.root.comments_aggregate" ON ('true')      ) AS "_5_root"
postgres_1        | 	            ) _fld_resp ON ('true')
```
Seems like when using the subscription some kind of parse error is happening.

I also started a discussion about this recently on Discord and another user confirmed the same issue.

### PR DESCRIPTION
**Pull request by abooij**
### Description

PR #3344 fixes #3239, which was an issue caused by an oversight in how we generate SQL for geographic input. The oversight was caused by the lack of testing of subscriptions. This PR is a rebase of #3344, so that #3239 is fixed, and additionally implements the suggested flag indicating that we are exploiting an internal feature (see below). 

### Changelog

- [x] `CHANGELOG.md` is updated with user-facing content relevant to this PR.

### Affected components

- [x] Server
- [x] Tests

### Solution and Design

As in #3344, the actual fix is minimal (see `server/src-lib/Hasura/GraphQL/Execute/LiveQuery/Plan.hs`). The remainder of the PR consists of allowing easy testing of subscriptions by adding a `subscription` "transport" type to the test suite that changes a `query` GraphQL query to a `subscription`. Many `query` type tests use multiple root fields, which are not allowed by the GraphQL standard. So, rather than splitting them up, the easiest way to re-use these tests is to simply support subscriptions with multiple root fields, thus departing from the GraphQL standard. To avoid users shooting themselves in the foot, this feature is only enabled if a `_multiple_subscriptions` flag is passed: so the test suite replaces `query` with `subscriptions` and adds `@_multiple_subscriptions` to the request. This internal flag is picked up by `validateGQ` in `server/src-lib/Hasura/GraphQL/Validate.hs`.

Example query:
```graphql
subscription mySub($arg : Int! = 2) @_multiple_subscriptions {
  article (where: {id: {_eq: $arg}}) {
    title
  }
  author {
    name
  }
}
```
### Steps to test and verify

The above implementation allowed an existing `query` test (see `TestGraphQLQueryBoolExpPostGIS` in `server/tests-py/test_graphql_queries.py`) to be re-used as a `subscription` test, so that we now have a regression test for this.

### Limitations, known bugs & workarounds

Users may shoot themselves in the foot if they somehow use the directive `@_multiple_subscriptions` for a different purpose. However, they normally shouldn't have access to directives, and our usage of them is very limited.

#### Catalog upgrade

Does this PR change Hasura Catalog version?
- [x] No

#### Metadata

Does this PR add a new Metadata feature?
- [x] No

#### GraphQL
- [x] No new GraphQL schema is generated

#### Breaking changes

- [x] No Breaking changes

### CODE REVIEW

File: server/src-lib/Hasura/GraphQL/Validate.hs [hunk 1]
```diff
@@ -172,12 +171,16 @@ validateGQ (QueryParts opDef opRoot fragDefsL varValsM) = do
...
-          unless (null rst) $
-            throwVE "subscription must select only one top level field"
-          return $ RSubscription fld
+      case selSet of
+        Seq.Empty       -> throw500 "empty selset for subscription"
+        (_ Seq.:<| rst) -> do
+          -- As an internal testing feature, we support subscribing to
+          -- multiple selection sets.  First check if the
+          -- corresponding directive is set.
+          let multipleAllowed = elem (G.Directive "_multiple_subscriptions" []) (G._todDirectives opDef)
```
Comment (0x777) [inline server/src-lib/Hasura/GraphQL/Validate.hs:180]: I would probably call it, `_multiple_top_level_fields`, your call though, I'm not particular about this. Formatting of the comment is as per the style guide (wrap it at 80 characters)?

Comment (abooij) [reply server/src-lib/Hasura/GraphQL/Validate.hs:180]: Formatting of the comment is as per Emacs' `M-q` :smile:.

I'll fix the formatting and rename the directive to `_multiple_top_level_fields`.
