### PR TITLE
fix remote queries/mutations to work over websocket (fix #1619) 

### LINKED ISSUE #1619: queries/mutations to remote server doesn't work over websockets
Currently, sending queries/mutations over websocket to remote schema server doesn't work.

### PR DESCRIPTION
**Pull request by ecthiender**
### Description

See issue #1619 . This was because the server was sending the wrong payload.

What component does this PR affect? 

- [x] Server
- [ ] Console
- [ ] CLI
- [ ] Docs
- [ ] Community Content
- [ ] Build System

Requires changes from other components? If yes, please mark the components:

- [ ] Server
- [ ] Console
- [ ] CLI
- [ ] Docs
- [ ] Community Content
- [ ] Build System

### Related Issue

#1619
### Solution and Design

The server was sending the websocket (apollo protocol) payload over http to the remote server. It should send the http payload.

### Type

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Docs update
- [ ] Community content

### Checklist:

- [ ] I have read the **[contributing guide](https://github.com/hasura/graphql-engine/blob/master/CONTRIBUTING.md)** and my code conforms to the guidelines.
- [ ] This change requires a change in the documentation. 
- [ ] I have updated the documentation accordingly.
- [x] I have added required tests.

### CODE REVIEW

File: server/src-lib/Hasura/GraphQL/Transport/WebSocket.hs [hunk 1]
```diff
@@ -218,6 +213,26 @@ onStart serverEnv wsConn (StartMsg opId q) msgRaw = catchAndIgnore $ do
...
+    runRemoteQ userInfo reqHdrs opDef rsi = do
+      when (G._todType opDef == G.OperationTypeSubscription) $
+        withComplete $ sendConnErr "subscription to remote server is not supported"
+
+      -- if it's not a subscription, use HTTP to execute the query on the remote
+      -- server
+      -- try to parse the (apollo protocol) websocket frame and get only the
+      -- payload
+      sockPayload <- onLeft (J.eitherDecode msgRaw) $
+        const $ withComplete $ sendConnErr "invalid websocket payload"
```
Comment (0x777) [inline server/src-lib/Hasura/GraphQL/Transport/WebSocket.hs]: This should be an internal error as we already parsed the request successfully?
