### PR TITLE
fix console insert/edit row glitches (close #2840, #2665)

### LINKED ISSUE #2840: 'default' radio button is disabled for identity columns
Create a table as follows:
```sql
CREATE TABLE public.page (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    title VARCHAR(100) NOT NULL
);
```
Head to insert row and try to insert data into it, you see that the 'default' is disabled:

image

If I try to insert data, I'll see this error:
```json
{
    "statement": "...",
    "prepared": true,
    "error": {
        "exec_status": "FatalError",
        "hint": "Use OVERRIDING SYSTEM VALUE to override.",
        "message": "cannot insert into column \"id\"",
        "status_code": "428C9",
        "description": "Column \"id\" is an identity column defined as GENERATED ALWAYS."
    },
    "arguments": [
        "(Oid 0,Just (\"\",Text))",
        "(Oid 25,Just (\"hello\",Binary))"
    ]
}
```
If you edit the radio button and enable it you can insert into this table. I'm guessing the console disables the `default` radio button if it can't find a default value for columns. With identity columns, there is no default as such. I guess we can always enable the `default` radio button in the console.

### PR DESCRIPTION
**Pull request by rikinsk13**
### Description

- Handle identity columns in insert / edit row
- Handle object content columns in edit row
- Create new tab for edit row
- Disable Null and Default options in edit row based on column properties
- italicize views in untracked section _(sneaking this in as not worthy of a separate PR)_

- refactor Table header

### Affected components 

- Console

### Related Issues

#2840, #2665

### CODE REVIEW

File: console/src/components/Common/utils/pgUtils.js [hunk 1]
```diff
@@ -77,6 +77,17 @@ export const getTrackedTables = tables => {
   return tables.filter(t => t.is_table_tracked);
 };
 
+export const isColumnAutoIncrement = column => {
```
Comment (wawhal) [inline console/src/components/Common/utils/pgUtils.js]: We sure this is the foolproof way of checking autoIncrement?
Because the sequence could refer to a custom sequence too. We should be wary of that since we support existing databases.

Something like this would be safer? What do you think? Its a false-negative vs false-positive problem.

```js
column.column_default && column.column_default.includes("_seq'::regclass)");
```

File: console/src/components/Services/Data/TableCommon/TableHeader.js [hunk 2]
```diff
@@ -99,7 +104,7 @@ const TableHeader = ({
                 }
                 data-test="table-insert-rows"
               >
-                Insert Row
+                {tabName === 'edit' ? 'Edit' : 'Insert'} Row
```
Comment (wawhal) [inline console/src/components/Services/Data/TableCommon/TableHeader.js]: Can we just have an extra tab called `Edit` "only" at the `:tableName/edit` route?
Tabs magically switching functionalities is a bit confusing.
